#include <iostream>

int main()
{
    // ifdef-guard header
    std::cout << "#ifndef KEMFIELD_OPENCL_DEFINES_H" << std::endl;
    std::cout << "#define KEMFIELD_OPENCL_DEFINES_H" << std::endl;
    std::cout << std::endl;
    std::cout << "/* NOTE: this file has been autogenerated by the program \"GenerateOpenCLHeader\"" << std::endl;
    std::cout << "         at build time.  Any changes to this file will be erased when KEMField" << std::endl;
    std::cout << "         is re-installed! */" << std::endl;
    std::cout << std::endl;

    std::cout << "#if defined(cl_khr_fp64)" << std::endl;
    std::cout << "#pragma OPENCL EXTENSION cl_khr_fp64 : enable" << std::endl;
    std::cout << "#elif defined(cl_amd_fp64)" << std::endl;
    std::cout << "#pragma OPENCL EXTENSION cl_amd_fp64 : enable" << std::endl;
    std::cout << "#else" << std::endl;
    std::cout << "#error \"KEMField OpenCL kernels require double precision support.\"" << std::endl;
    std::cout << "#endif" << std::endl;
    std::cout << std::endl;

    std::cout << "#define KEMFIELD_DEFAULT_GPU_ID 0" << std::endl;
    std::cout << "#define KEMFIELD_USE_DOUBLE_PRECISION" << std::endl;
    std::cout << "#define CL_TYPE double" << std::endl;
    std::cout << "#define CL_TYPE2 double2" << std::endl;
    std::cout << "#define CL_TYPE4 double4" << std::endl;
    std::cout << "#define CL_TYPE8 double8" << std::endl;
    std::cout << "#define CL_TYPE16 double16" << std::endl;
    std::cout << "#define SQRT(x) sqrt(x)" << std::endl;
    std::cout << "#define LOG(x) log(x)" << std::endl;
    std::cout << "#define MAX_ASINH_ARG 1.0e307" << std::endl;

    // definition of constants
    std::cout << "#define M_EPS0 8.854187817E-12" << std::endl;
    std::cout << "#define M_PI_OVER_2 1.57079632679489661923" << std::endl;
    std::cout << "#define M_ONEOVER_4PI_EPS0 8987551787.9979107161559640186992" << std::endl;

    // mathematical operations
    std::cout << "#define POW2(x) ((x)*(x))" << std::endl;
    std::cout << "#define POW3(x) ((x)*(x)*(x))" << std::endl;

    // complete ifdef-guard header
    std::cout << std::endl;
    std::cout << "#endif /* KEMFIELD_OPENCL_DEFINES_H */" << std::endl;

    return 0;
}
