name: Build & Test Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main_image_build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build target "build"
      run: |
        docker build --target build \
          --build-arg KASSIOPEIA_GIT_BRANCH=$GITHUB_REF_NAME \
          --build-arg KASSIOPEIA_GIT_COMMIT=$GITHUB_SHA  \
          --build-arg KASSIOPEIA_CPUS=$(nproc)  \
          -t kasper_build .
        
    - name: Build target "minimal"
      run: |
        docker build --target minimal \
          --build-arg KASSIOPEIA_GIT_BRANCH=$GITHUB_REF_NAME \
          --build-arg KASSIOPEIA_GIT_COMMIT=$GITHUB_SHA  \
          --build-arg KASSIOPEIA_CPUS=$(nproc)  \
          -t kasper_minimal .
    
    - name: UnitTestKasper in "minimal"
      run: docker run --rm -t kasper_minimal UnitTestKasper
    
    - name: Build target "full"
      run: |
        echo Build target "full"
        docker build --target full \
          --build-arg KASSIOPEIA_GIT_BRANCH=$GITHUB_REF_NAME \
          --build-arg KASSIOPEIA_GIT_COMMIT=$GITHUB_SHA  \
          --build-arg KASSIOPEIA_CPUS=$(nproc)  \
          -t kasper_full .
    
    - name: UnitTestKasper in "full"
      run: docker run --rm -t kasper_full UnitTestKasper
